#!/usr/bin/env node
/**
 * Embeds portfolio woff2 files as base64 data URIs in CSS.
 *
 * Safari content blockers (resource type "font") can block same-origin .woff2
 * fetches. Fonts inlined as data: URLs cannot be blocked that way
 * (see SansFonts / AdGuard $font docs).
 *
 * Usage: node scripts/embed-fonts.cjs
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const fontsDir = path.join(root, "app/fonts");
const outPath = path.join(fontsDir, "embedded.css");

function dataUri(filename) {
  const bytes = fs.readFileSync(path.join(fontsDir, filename));
  return `url(data:font/woff2;base64,${bytes.toString("base64")}) format("woff2")`;
}

const css = `/* AUTO-GENERATED by scripts/embed-fonts.cjs — do not edit by hand.
 * Re-run: npm run fonts:embed
 *
 * Inlined so iOS Safari content blockers cannot strip font network requests.
 */

@font-face {
  font-family: "Portfolio Display";
  src: ${dataUri("fraunces-variable.woff2")};
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: "Portfolio Sans";
  src: ${dataUri("space-grotesk-variable.woff2")};
  font-weight: 300 700;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: "Portfolio Mono";
  src: ${dataUri("space-mono-400.woff2")};
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: "Portfolio Mono";
  src: ${dataUri("space-mono-700.woff2")};
  font-weight: 700;
  font-style: normal;
  font-display: swap;
}

:root {
  --font-display: "Portfolio Display", "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
  --font-sans: "Portfolio Sans", system-ui, "Segoe UI", Roboto, sans-serif;
  --font-mono: "Portfolio Mono", ui-monospace, "SFMono-Regular", Menlo, monospace;
}
`;

fs.writeFileSync(outPath, css);
const kb = (fs.statSync(outPath).size / 1024).toFixed(1);
console.log(`Wrote ${outPath} (${kb} KB)`);
